<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.test.NIMS.data_provider.LoginUserDataProvider" tests="1" time="0.000" ignored="7" failures="0" timestamp="27 Jun 2019 09:22:06 GMT" skipped="0" hostname="Vuyo-HP" errors="1">
  <testcase name="loginData" time="0.000" classname="com.test.NIMS.data_provider.LoginUserDataProvider">
    <error type="java.io.FileNotFoundException" message="C:\Users\Vuyo\Documents\Neo\SOWWorkhead.xlsx (The system cannot find the file specified)">
      <![CDATA[java.io.FileNotFoundException: C:\Users\Vuyo\Documents\Neo\SOWWorkhead.xlsx (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.test.NIMS.data_provider.BaseProvider.readExcel(BaseProvider.java:29)
	at com.test.NIMS.data_provider.LoginUserDataProvider.loginData(LoginUserDataProvider.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.TestRunner.beforeRun(TestRunner.java:634)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- loginData -->
  <testcase name="testNavigateToReportProblem" classname="pages.MainMenu.MainMenu">
    <skipped/>
  </testcase> <!-- testNavigateToReportProblem -->
  <testcase name="testNavigateToPendingSOWWorkHead" classname="pages.AdminMainMenu.TestAdminMenu">
    <skipped/>
  </testcase> <!-- testNavigateToPendingSOWWorkHead -->
  <testcase name="testLogout" classname="pages.SOWDetails.TestSOWDetails">
    <skipped/>
  </testcase> <!-- testLogout -->
  <testcase name="testLogout" classname="pages.ReportProblem.ReportProblem">
    <skipped/>
  </testcase> <!-- testLogout -->
  <testcase name="testSubmitReportProblem" classname="pages.ReportProblem.ReportProblem">
    <skipped/>
  </testcase> <!-- testSubmitReportProblem -->
  <testcase name="testLoginAdmin2" classname="pages.LoginAdmin.TestLoginAdmin">
    <skipped/>
  </testcase> <!-- testLoginAdmin2 -->
  <testcase name="testSearchForProbleByProblemNumber" classname="pages.OpenRequests.TestOpenRequests">
    <skipped/>
  </testcase> <!-- testSearchForProbleByProblemNumber -->
</testsuite> <!-- com.test.NIMS.data_provider.LoginUserDataProvider -->
